# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dream Chronicle' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dream Chronicle

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  
  target 'Dream ChronicleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Dream ChronicleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
